name: CMake

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PROJECT_NAME: LockOn2MapPin
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VCPKG_FEATURE_FLAGS: "manifests,versions"
  VCPKG_DISABLE_METRICS: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
        vcpkgGitCommitId: 75522bb1f2e7d863078bcd06322348f053a9e33f

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -S . -B build/ -A x64

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build build/ --config $BUILD_TYPE

#     - name: Test
#       working-directory: ${{runner.workspace}}/build
#       shell: bash
#       # Execute tests defined by the CMake configuration.
#       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#       run: ctest -C $BUILD_TYPE

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }} Release
        path: ./build/src/Release/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      git_tag: ${{ steps.set_vars.outputs.git_tag }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }} Release

    - name: Zip it
      run: |
        mkdir -p nativePC/plugins/
        mv $PROJECT_NAME.dll \
           nativePC/plugins
        zip $PROJECT_NAME.zip -r nativePC/ yaml-cpp.dll

    - name: Update changelog and bump version
      id: set_vars
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        wget -nc -q -O Changelog.md https://raw.githubusercontent.com/wiki/$GITHUB_REPOSITORY/Changelog.md || true
        npx standard-version --silent --dry-run | sed '/---/d' > notes.md
        npx standard-version

        GIT_TAG=$(cat notes.md | grep -o "\[.*\]" -m 1 | tail -n1)
        GIT_TAG=${GIT_TAG#[}
        GIT_TAG=${GIT_TAG%]}
        echo "GIT_TAG=v$GIT_TAG" >> $GITHUB_ENV
        echo "::set-output name=git_tag::v$GIT_TAG"

    - name: Create release with binaries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create $GIT_TAG -t "Release $GIT_TAG" --notes-file notes.md \
           *.zip \
           nativePC/plugins/*.dll

    - name: Upload Changelog
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }} Changelog
        path: Changelog.md

  wiki:
    needs: publish
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki

    - name: Download Changelog
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }} Changelog

    - name: Commit changes and push
      env:
        GIT_TAG: ${{ needs.publish.outputs.git_tag }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if (test $(git diff --numstat | cut -f1) -gt 2)
        then
          git config user.name "Github Actions"
          git config user.email action@github.com
          git add -A
          git commit -m "update wiki for $GIT_TAG"
          git tag -a $GIT_TAG -m "$GIT_TAG"
          git push --follow-tags origin master
        else
          echo "No notable changes in this release"
          git reset --hard HEAD
        fi

  next:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - name: Trigger MHW-Plugins workflow
      env:
        GITHUB_TOKEN: ${{ secrets.MHWPLUGINS }}
        REPO_OWNER: ${{ github.repository_owner }}
      run: |
        curl -X POST \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: token $GITHUB_TOKEN" \
             -d '{"ref":"master"}' \
             https://api.github.com/repos/$REPO_OWNER/MHW-Plugins/actions/workflows/pack.yml/dispatches
